// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VivuqeQRSystem.Data;

#nullable disable

namespace VivuqeQRSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212154006_AddTicketMessageCustomization")]
    partial class AddTicketMessageCustomization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("VivuqeQRSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketDateDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketLocationDisplay")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketMapUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketTimeDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketWelcomeMessage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttendanceTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeniorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketToken")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GuestId");

                    b.HasIndex("SeniorId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Senior", b =>
                {
                    b.Property<int>("SeniorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SeniorId");

                    b.HasIndex("EventId");

                    b.ToTable("Seniors");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEventId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Guest", b =>
                {
                    b.HasOne("VivuqeQRSystem.Models.Senior", "Senior")
                        .WithMany("Guests")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Senior", b =>
                {
                    b.HasOne("VivuqeQRSystem.Models.Event", "Event")
                        .WithMany("Seniors")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.User", b =>
                {
                    b.HasOne("VivuqeQRSystem.Models.Event", "AssignedEvent")
                        .WithMany()
                        .HasForeignKey("AssignedEventId");

                    b.Navigation("AssignedEvent");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Event", b =>
                {
                    b.Navigation("Seniors");
                });

            modelBuilder.Entity("VivuqeQRSystem.Models.Senior", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
